# Generated by Django 5.2.7 on 2026-04-08 23:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('commissioner_email', models.EmailField(max_length=254)),
                ('max_players', models.PositiveSmallIntegerField(default=4)),
                ('status', models.CharField(choices=[('SETUP', 'Setup'), ('DRAFTING', 'Drafting'), ('ACTIVE', 'Active')], default='SETUP', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETE', 'Complete')], default='NOT_STARTED', max_length=20)),
                ('draft_type', models.CharField(choices=[('SNAKE', 'Snake'), ('OFFLINE', 'Offline'), ('AUTOPICK', 'Autopick'), ('SALARY_CAP', 'Salary Cap')], default='SNAKE', max_length=20)),
                ('scheduled_date', models.DateTimeField(blank=True, null=True)),
                ('time_per_pick', models.PositiveIntegerField(default=90, help_text='Time in seconds')),
                ('draft_order', models.CharField(choices=[('RANDOM', 'Randomized One Hour Prior to Draft Time'), ('CUSTOM', 'Custom Draft Order')], default='RANDOM', max_length=20)),
                ('current_slot', models.PositiveSmallIntegerField(default=1)),
                ('round', models.PositiveIntegerField(default=1)),
                ('pick_number', models.PositiveIntegerField(default=1)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('league', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='draft', to='league.league')),
            ],
        ),
        migrations.CreateModel(
            name='LeagueMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('display_name', models.CharField(blank=True, max_length=80)),
                ('slot', models.PositiveSmallIntegerField()),
                ('is_commissioner', models.BooleanField(default=False)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='league.league')),
            ],
            options={
                'ordering': ['slot'],
                'unique_together': {('league', 'email')},
            },
        ),
        migrations.CreateModel(
            name='FantasyTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My Team', max_length=120)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='league.league')),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='league.leaguemember')),
            ],
        ),
        migrations.CreateModel(
            name='FantasyTeamPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquired_via', models.CharField(choices=[('DRAFT', 'Draft'), ('TRADE', 'Trade'), ('FREE_AGENT', 'Free Agent')], default='DRAFT', max_length=20)),
                ('acquired_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fantasy_roster_entries', to='players.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster', to='league.fantasyteam')),
            ],
            options={
                'unique_together': {('team', 'player')},
            },
        ),
        migrations.CreateModel(
            name='DraftPick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_number', models.PositiveIntegerField()),
                ('round', models.PositiveIntegerField()),
                ('slot', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picks', to='league.draft')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafted_picks', to='players.player')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.leaguemember')),
            ],
            options={
                'ordering': ['pick_number'],
                'unique_together': {('draft', 'pick_number'), ('draft', 'player')},
            },
        ),
    ]
