# Generated by Django 5.2.7 on 2026-04-11 02:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0001_initial'),
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='league.league')),
                ('proposed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades_proposed', to='league.leaguemember')),
                ('proposed_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades_received', to='league.leaguemember')),
            ],
        ),
        migrations.CreateModel(
            name='TradePlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.leaguemember')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.player')),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_players', to='league.trade')),
            ],
            options={
                'unique_together': {('trade', 'player')},
            },
        ),
    ]
