# Generated by Django 5.2.7 on 2026-04-20 16:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0002_trade_tradeplayer'),
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='status',
            field=models.CharField(choices=[('SETUP', 'Setup'), ('DRAFTING', 'Drafting'), ('ACTIVE', 'Active'), ('PLAYOFFS', 'Playoffs')], default='SETUP', max_length=20),
        ),
        migrations.CreateModel(
            name='Playoff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETE', 'Complete')], default='NOT_STARTED', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('league', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='playoff', to='league.league')),
            ],
        ),
        migrations.CreateModel(
            name='PlayoffMatchup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.CharField(choices=[('SEMIFINAL', 'Semifinal'), ('FINAL', 'Final')], max_length=20)),
                ('team_a_score', models.FloatField(blank=True, null=True)),
                ('team_b_score', models.FloatField(blank=True, null=True)),
                ('simulated', models.BooleanField(default=False)),
                ('playoff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchups', to='league.playoff')),
                ('team_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchups_as_a', to='league.fantasyteam')),
                ('team_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchups_as_b', to='league.fantasyteam')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matchups_won', to='league.fantasyteam')),
            ],
            options={
                'ordering': ['round', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PlayerMatchupStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pts', models.FloatField()),
                ('reb', models.FloatField()),
                ('ast', models.FloatField()),
                ('fantasy_score', models.FloatField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchup_stats', to='players.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchup_stats', to='league.fantasyteam')),
                ('matchup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to='league.playoffmatchup')),
            ],
            options={
                'unique_together': {('matchup', 'player')},
            },
        ),
    ]
