# Generated by Django 5.2.7 on 2026-04-20 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0003_alter_league_status_playoff_playoffmatchup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='status',
            field=models.CharField(choices=[('SETUP', 'Setup'), ('DRAFTING', 'Drafting'), ('ACTIVE', 'Active'), ('PLAYOFFS', 'Playoffs'), ('COMPLETE', 'Complete')], default='SETUP', max_length=20),
        ),
    ]
