# Generated by Django 5.2.7 on 2026-04-20 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0004_alter_league_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='playoff',
            name='champion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='championships_won', to='league.fantasyteam'),
        ),
    ]
