# Generated by Django 5.2.7 on 2026-04-22 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0005_playoff_champion'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='roster_size',
            field=models.PositiveSmallIntegerField(default=12),
        ),
    ]
