# Generated by Django 5.2.7 on 2026-04-08 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.IntegerField(unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('first_name', models.CharField(blank=True, max_length=128)),
                ('last_name', models.CharField(blank=True, max_length=128)),
                ('team_name', models.CharField(blank=True, max_length=100, null=True)),
                ('team_abbreviation', models.CharField(blank=True, max_length=10, null=True)),
                ('position', models.CharField(blank=True, max_length=10)),
                ('height', models.CharField(blank=True, max_length=20)),
                ('weight', models.CharField(blank=True, max_length=20, null=True)),
                ('jersey_number', models.CharField(blank=True, max_length=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('roster_status', models.CharField(choices=[('FA', 'Free Agent'), ('RW', 'On Waivers'), ('IL', 'Injured List'), ('R', 'Active')], default='FA', max_length=2)),
                ('injury_status', models.CharField(blank=True, max_length=255, null=True)),
                ('is_healthy', models.BooleanField(default=True)),
                ('roster_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=10)),
                ('period_type', models.CharField(choices=[('season', 'Season'), ('last7', 'Last 7 Days'), ('last15', 'Last 15 Days'), ('last30', 'Last 30 Days')], default='season', max_length=20)),
                ('games_played', models.IntegerField(default=0)),
                ('min_total', models.DecimalField(decimal_places=1, default=0, max_digits=10)),
                ('min_avg', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('fgm_total', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('fga_total', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('fg_pct', models.DecimalField(decimal_places=3, default=0, max_digits=5)),
                ('fgm_avg', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('fga_avg', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('ftm_total', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('fta_total', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('ft_pct', models.DecimalField(decimal_places=3, default=0, max_digits=5)),
                ('ftm_avg', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('fta_avg', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('fg3m_total', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('fg3a_total', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('fg3_pct', models.DecimalField(decimal_places=3, default=0, max_digits=5)),
                ('fg3m_avg', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('reb_total', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('reb_avg', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('oreb_total', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('dreb_total', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('ast_total', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('ast_avg', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('stl_total', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('stl_avg', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('blk_total', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('blk_avg', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('tov_total', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('tov_avg', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('pts_total', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('pts_avg', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('plus_minus_total', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('plus_minus_avg', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('fantasy_points_total', models.DecimalField(decimal_places=1, default=0, max_digits=10)),
                ('fantasy_points_avg', models.DecimalField(decimal_places=1, default=0, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='nba_players.player')),
            ],
            options={
                'ordering': ['-season', 'period_type'],
                'unique_together': {('player', 'season', 'period_type')},
            },
        ),
    ]
