# Generated by Django 5.2.11 on 2026-02-22 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba_players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstats',
            name='fantasy_points_avg',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='playerstats',
            name='fantasy_points_total',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10),
        ),
    ]
