# Generated by Django 6.0.3 on 2026-05-04 07:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('season_label', models.CharField(default='2025-26', max_length=20)),
                ('status', models.CharField(choices=[('setup', 'Setup'), ('drafting', 'Drafting'), ('regular', 'Regular Season'), ('playoffs', 'Playoffs'), ('complete', 'Complete')], default='setup', max_length=12)),
                ('max_teams', models.IntegerField(default=8, validators=[django.core.validators.MinValueValidator(2)])),
                ('regular_season_weeks', models.IntegerField(default=6, validators=[django.core.validators.MinValueValidator(2)])),
                ('playoff_team_count', models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(2)])),
                ('scoring_weights', models.JSONField(default=dict)),
                ('roster_template', models.JSONField(default=list)),
                ('lineup_lock_mode', models.CharField(choices=[('weekly', 'Weekly'), ('daily', 'Daily (game-time)')], default='weekly', max_length=8)),
                ('trade_review_mode', models.CharField(choices=[('auto', 'Auto-process on accept'), ('commissioner', 'Commissioner review'), ('league_vote', 'League vote')], default='auto', max_length=16)),
                ('invite_code', models.CharField(db_index=True, max_length=12, unique=True)),
                ('current_week_number', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('commissioner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commissioned_leagues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('complete', 'Complete')], default='not_started', max_length=12)),
                ('draft_order', models.JSONField(default=list, help_text='Ordered list of LeagueMember ids representing the first-round pick order.')),
                ('current_pick_index', models.IntegerField(default=0, help_text='0-based pointer into the snake order.')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('league', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='draft', to='fantasy.league')),
            ],
        ),
        migrations.CreateModel(
            name='LeagueMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_bot', models.BooleanField(default=False)),
                ('bot_name', models.CharField(blank=True, max_length=120)),
                ('is_commissioner', models.BooleanField(default=False)),
                ('slot', models.IntegerField(help_text='1-indexed draft order slot')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='fantasy.league')),
                ('user', models.ForeignKey(blank=True, help_text='Null for bot members.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='league_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('league_id', 'slot'),
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('full_name', models.CharField(max_length=120)),
                ('first_name', models.CharField(blank=True, max_length=80)),
                ('last_name', models.CharField(blank=True, max_length=80)),
                ('team_abbr', models.CharField(blank=True, max_length=8)),
                ('primary_position', models.CharField(blank=True, help_text='One of PG / SG / SF / PF / C', max_length=4)),
                ('eligible_positions', models.JSONField(blank=True, default=list, help_text='List of positions the player can fill, e.g. ["SF", "PF"]')),
                ('is_active', models.BooleanField(default=True)),
                ('is_injured', models.BooleanField(default=False)),
                ('injury_status', models.CharField(blank=True, max_length=200)),
                ('bbref_id', models.CharField(blank=True, db_index=True, max_length=40)),
                ('nba_player_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('last_name', 'first_name'),
                'indexes': [models.Index(fields=['team_abbr'], name='fantasy_pla_team_ab_33bfbd_idx'), models.Index(fields=['primary_position'], name='fantasy_pla_primary_cabeff_idx')],
            },
        ),
        migrations.CreateModel(
            name='DraftSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_number', models.IntegerField(help_text='1-indexed overall pick number.')),
                ('round_number', models.IntegerField()),
                ('selected_at', models.DateTimeField(auto_now_add=True)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='fantasy.draft')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_picks', to='fantasy.leaguemember')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafted_in', to='fantasy.player')),
            ],
            options={
                'ordering': ('draft_id', 'pick_number'),
            },
        ),
        migrations.CreateModel(
            name='PlayerGameStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_date', models.DateField(db_index=True)),
                ('minutes', models.FloatField(default=0)),
                ('pts', models.FloatField(default=0)),
                ('reb', models.FloatField(default=0)),
                ('ast', models.FloatField(default=0)),
                ('stl', models.FloatField(default=0)),
                ('blk', models.FloatField(default=0)),
                ('tov', models.FloatField(default=0)),
                ('fgm', models.FloatField(default=0)),
                ('fga', models.FloatField(default=0)),
                ('ftm', models.FloatField(default=0)),
                ('fta', models.FloatField(default=0)),
                ('fg3m', models.FloatField(default=0)),
                ('did_play', models.BooleanField(default=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_stats', to='fantasy.player')),
            ],
            options={
                'ordering': ('-game_date',),
            },
        ),
        migrations.CreateModel(
            name='PlayerSeasonAverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(help_text='Season label, e.g. "2025-26"', max_length=10)),
                ('games_played', models.IntegerField(default=0)),
                ('minutes', models.FloatField(default=0)),
                ('pts', models.FloatField(default=0)),
                ('reb', models.FloatField(default=0)),
                ('ast', models.FloatField(default=0)),
                ('stl', models.FloatField(default=0)),
                ('blk', models.FloatField(default=0)),
                ('tov', models.FloatField(default=0)),
                ('fgm', models.FloatField(default=0)),
                ('fga', models.FloatField(default=0)),
                ('ftm', models.FloatField(default=0)),
                ('fta', models.FloatField(default=0)),
                ('fg3m', models.FloatField(default=0)),
                ('fg3a', models.FloatField(default=0)),
                ('fg_pct', models.FloatField(default=0)),
                ('ft_pct', models.FloatField(default=0)),
                ('fg3_pct', models.FloatField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_averages', to='fantasy.player')),
            ],
            options={
                'ordering': ('-pts',),
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('ties', models.IntegerField(default=0)),
                ('points_for', models.FloatField(default=0)),
                ('points_against', models.FloatField(default=0)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='fantasy.league')),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='fantasy.leaguemember')),
            ],
            options={
                'ordering': ('-wins', '-points_for'),
            },
        ),
        migrations.CreateModel(
            name='Roster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquired_at', models.DateTimeField(auto_now_add=True)),
                ('acquired_via', models.CharField(choices=[('draft', 'Draft'), ('trade', 'Trade'), ('free_agent', 'Free agent')], default='draft', max_length=12)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster_entries', to='fantasy.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster_entries', to='fantasy.team')),
            ],
            options={
                'ordering': ('team_id', 'acquired_at'),
            },
        ),
        migrations.CreateModel(
            name='LineupEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_date', models.DateField()),
                ('slot', models.CharField(max_length=12)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineup_entries', to='fantasy.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineup_entries', to='fantasy.team')),
            ],
            options={
                'ordering': ('game_date', 'team_id', 'slot'),
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('processed', 'Processed')], default='proposed', max_length=12)),
                ('proposed_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=400)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='fantasy.league')),
                ('proposer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades_proposed', to='fantasy.team')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades_received', to='fantasy.team')),
            ],
            options={
                'ordering': ('-proposed_at',),
            },
        ),
        migrations.CreateModel(
            name='TradeAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_assets_out', to='fantasy.team')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_assets', to='fantasy.player')),
                ('to_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_assets_in', to='fantasy.team')),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='fantasy.trade')),
            ],
            options={
                'ordering': ('trade_id', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('draft_pick', 'Draft pick'), ('trade', 'Trade'), ('lineup_set', 'Lineup set'), ('week_advanced', 'Week advanced'), ('commissioner_override', 'Commissioner override'), ('other', 'Other')], max_length=24)),
                ('summary', models.CharField(max_length=400)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='fantasy.league')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='fantasy.team')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_playoff', models.BooleanField(default=False)),
                ('playoff_round', models.CharField(blank=True, help_text='e.g. "semifinal", "final"', max_length=20)),
                ('is_settled', models.BooleanField(default=False, help_text='Set after matchup scores are computed and standings updated.')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='fantasy.league')),
            ],
            options={
                'ordering': ('league_id', 'week_number'),
            },
        ),
        migrations.CreateModel(
            name='Matchup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_score', models.FloatField(default=0)),
                ('away_score', models.FloatField(default=0)),
                ('is_settled', models.BooleanField(default=False)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchups_as_away', to='fantasy.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchups_as_home', to='fantasy.team')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matchups_won', to='fantasy.team')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchups', to='fantasy.week')),
            ],
            options={
                'ordering': ('week_id', 'id'),
            },
        ),
        migrations.AddConstraint(
            model_name='leaguemember',
            constraint=models.UniqueConstraint(fields=('league', 'slot'), name='uniq_member_league_slot'),
        ),
        migrations.AddConstraint(
            model_name='leaguemember',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('league', 'user'), name='uniq_member_league_user'),
        ),
        migrations.AddConstraint(
            model_name='draftselection',
            constraint=models.UniqueConstraint(fields=('draft', 'pick_number'), name='uniq_pick_draft_number'),
        ),
        migrations.AddConstraint(
            model_name='draftselection',
            constraint=models.UniqueConstraint(fields=('draft', 'player'), name='uniq_pick_draft_player'),
        ),
        migrations.AddConstraint(
            model_name='playergamestats',
            constraint=models.UniqueConstraint(fields=('player', 'game_date'), name='uniq_gamestats_player_date'),
        ),
        migrations.AddConstraint(
            model_name='playerseasonaverage',
            constraint=models.UniqueConstraint(fields=('player', 'season'), name='uniq_seasonavg_player_season'),
        ),
        migrations.AddConstraint(
            model_name='roster',
            constraint=models.UniqueConstraint(fields=('team', 'player'), name='uniq_roster_team_player'),
        ),
        migrations.AddConstraint(
            model_name='lineupentry',
            constraint=models.UniqueConstraint(fields=('team', 'game_date', 'slot'), name='uniq_lineup_team_date_slot'),
        ),
        migrations.AddConstraint(
            model_name='lineupentry',
            constraint=models.UniqueConstraint(fields=('team', 'game_date', 'player'), name='uniq_lineup_team_date_player'),
        ),
        migrations.AddConstraint(
            model_name='week',
            constraint=models.UniqueConstraint(fields=('league', 'week_number'), name='uniq_week_league_number'),
        ),
    ]
