# Generated by Django 6.0.3 on 2026-05-04 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='height_inches',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='jersey_number',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='player',
            name='weight_lbs',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
