# Generated by Django 6.0.3 on 2026-05-04 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0002_player_height_inches_player_jersey_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='is_paused',
            field=models.BooleanField(default=False, help_text='Commissioner-controlled pause flag — bots stop auto-filling while true.'),
        ),
    ]
