# Generated by Django 6.0.3 on 2026-05-04 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0003_draft_is_paused'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('draft_pick', 'Draft pick'), ('trade', 'Trade'), ('trade_proposed', 'Trade proposed'), ('trade_rejected', 'Trade rejected'), ('trade_cancelled', 'Trade cancelled'), ('lineup_set', 'Lineup set'), ('week_advanced', 'Week advanced'), ('commissioner_override', 'Commissioner override'), ('other', 'Other')], max_length=24),
        ),
    ]
