from django.urls import path

from .views import (
    LeagueListCreate,
    SeedExampleLeague,
    LeagueDetail,
    DraftSettings,
    DraftSettingsReset,
    FillLeagueWithBots,
    AutoDraftLeague,
    StartDraft,
    MakePick,
    LeagueTeams,
    ResetLeague,
    LeagueTrades,
    ProposeTrade,
    TradeDetail,
    AcceptTrade,
    RejectTrade,
    CancelTrade,
    StartPlayoffs,
    PlayoffBracket,
    SimulateMatchup,
)

urlpatterns = [
    path("leagues/", LeagueListCreate.as_view(), name="league-list-create"),
    path("leagues/seed-example/", SeedExampleLeague.as_view(), name="league-seed-example"),
    path("leagues/<int:league_id>/", LeagueDetail.as_view(), name="league-detail"),
    path("leagues/<int:league_id>/start-draft/", StartDraft.as_view(), name="league-start-draft"),
    path("leagues/<int:league_id>/draft-settings/", DraftSettings.as_view(), name="league-draft-settings"),
    path("leagues/<int:league_id>/draft-settings/reset/", DraftSettingsReset.as_view(), name="league-draft-settings-reset"),
    path("leagues/<int:league_id>/fill-bots/", FillLeagueWithBots.as_view(), name="league-fill-bots"),
    path("leagues/<int:league_id>/auto-draft/", AutoDraftLeague.as_view(), name="league-auto-draft"),
    path("leagues/<int:league_id>/pick/", MakePick.as_view(), name="league-make-pick"),
    path("leagues/<int:league_id>/teams/", LeagueTeams.as_view(), name="league-teams"),
    path("leagues/<int:league_id>/reset/", ResetLeague.as_view(), name="league-reset"),
    path("leagues/<int:league_id>/trades/", LeagueTrades.as_view(), name="league-trades"),
    path("leagues/<int:league_id>/trades/propose/", ProposeTrade.as_view(), name="league-trade-propose"),
    path("trades/<int:trade_id>/", TradeDetail.as_view(), name="trade-detail"),
    path("trades/<int:trade_id>/accept/", AcceptTrade.as_view(), name="trade-accept"),
    path("trades/<int:trade_id>/reject/", RejectTrade.as_view(), name="trade-reject"),
    path("trades/<int:trade_id>/cancel/", CancelTrade.as_view(), name="trade-cancel"),
    # Playoffs
    path("leagues/<int:league_id>/start-playoffs/", StartPlayoffs.as_view(), name="league-start-playoffs"),
    path("leagues/<int:league_id>/bracket/", PlayoffBracket.as_view(), name="league-bracket"),
    path("leagues/<int:league_id>/matchups/<int:matchup_id>/simulate/", SimulateMatchup.as_view(), name="league-simulate-matchup"),
]