# Generated by Django 5.2.7 on 2026-04-08 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_id', models.IntegerField(unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=120)),
                ('player_slug', models.SlugField(max_length=120, unique=True)),
                ('team_id', models.IntegerField(blank=True, null=True)),
                ('team_slug', models.CharField(blank=True, max_length=50)),
                ('team_city', models.CharField(blank=True, max_length=50)),
                ('team_name', models.CharField(blank=True, max_length=50)),
                ('team_abbreviation', models.CharField(blank=True, max_length=10)),
                ('jersey_number', models.CharField(blank=True, max_length=10)),
                ('position', models.CharField(blank=True, max_length=10)),
                ('height', models.CharField(blank=True, max_length=10)),
                ('weight', models.CharField(blank=True, max_length=10)),
                ('college', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('draft_year', models.IntegerField(blank=True, null=True)),
                ('draft_round', models.IntegerField(blank=True, null=True)),
                ('draft_number', models.IntegerField(blank=True, null=True)),
                ('roster_status', models.BooleanField(default=True)),
                ('from_year', models.CharField(blank=True, max_length=10)),
                ('to_year', models.CharField(blank=True, max_length=10)),
                ('pts', models.FloatField(blank=True, null=True)),
                ('reb', models.FloatField(blank=True, null=True)),
                ('ast', models.FloatField(blank=True, null=True)),
                ('stats_timeframe', models.CharField(blank=True, max_length=30)),
                ('player_last_initial', models.CharField(blank=True, max_length=1)),
                ('historic', models.BooleanField(default=False)),
                ('is_defunct', models.BooleanField(default=False)),
            ],
        ),
    ]
