# Generated by Django 5.2.7 on 2026-04-27 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='specific_position',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
